name: yoyozamobile
description: COVID-19 e-Heath Screening

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  intl: ^0.16.1
  flutter_icons: ^1.0.0+1
  flutter_spinkit: ^4.1.2
  permission_handler: ^5.0.0+hotfix.3
  uuid: ^2.0.4
  path: ^1.6.4
  device_info: ^0.4.2+1
  shared_preferences: ^0.5.6+3
  modal_progress_hud: ^0.1.3
  intro_slider: ^2.3.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.8.1
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/yoyoza_logo.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf